### ISSUE TITLE
Integrate Github Actions

### ISSUE THREAD

**Issue by bransonf** [slu-openGIS/censusxy#22]
Github Actions seems like the path of least resistance long term. Supports all operating systems, and is *much* faster.

Linux is failing due to an outdated version of GDAL `<2.0.1`

MacOS is failing due to missing the `udunits` system dependency

Need to add code coverage secret to integrate coverage with Ghub actions. Also possible to build site automatically on commit. May be useful, especially if we want to separate the pkgdown website and serve from a `gh-pages` branch as opposed to master.

**Comment by bransonf** [comment]
Linux has been fixed. Interesting to note that a test failed for v3.3 because of a stale API call. Nothing practical we can do about that.

`MacOS - Devel` was removed until sf has a stable release. Currently an installation issue for an unknown version of R, to the best of my belief. Will need to be addressed with the next release of R (presumably 4.1)

Still outstanding is code coverage and building the site.

**Comment by chris-prener** [comment]
I love this. Nice work @bransonf! I want to explore just a bit more before we cut out the other CI tools. Will circle back to this next week.
