### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by chris-prener** [slu-openGIS/censusxy#27]
Tasks:

  1. [x] Set-up CI build on GitHub actions
  2. [x] Address build errors
  3. [x] Add `pkgdown` GitHub action for site build
  4. [x] `README.md` and repo housekeeping (remove old CI files, update badges)
  5. [ ] Ensure code coverage is working correctly

**Comment by bransonf** [comment]
@chris-prener just about all done, leaving README, badges and codecov to you.

We will have to do something about the pkgdown build action though. It pushes to master, which is likely going to result in git conflicts 😨 

I suggest we make a separate branch for the site, but that means we will need to reconfigure gh-pages. I can do that in this repo but not in the others. Either you will have to do this, or elevate my repo/org status.

**Comment by chris-prener** [comment]
interesting... let me do a little digging on the `pkgdown` thing before we decide on the best solution!
