### ISSUE TITLE
Issue with address batch n > 3

### ISSUE THREAD

**Issue by FCALVODBAMAF** [slu-openGIS/censusxy#29]
Hi,
I am currently trying to get the census tracts for a list of addresses.
When I ran this test with 3 addresses, I am able to get all information I need:
`geoids <- cxy_geocode(data.frame(street=c("2584 Haverford Dr","3964 Alemeny Blvd","3269 Mission St"), city=c("Troy","San Francisco","San Francisco"), state=c("MI","CA","CA"), postal_code=c("48098","94132","94110"), Id = c(1, 2, 3)), street = 'street', city = 'city', state = 'state', zip = 'postal_code',  return = 'geographies', class = 'dataframe', output = 'full', benchmark = "Public_AR_Census2020", vintage = "Census2020_Census2020")`

However, when I try the same code with a list of 851 addresses I get the following error:
`Error in curl::curl_fetch_memory(url, handle = handle) : 
  Empty reply from server`

Any idea as to why I am getting this error? Any help will be greatly appreciated

**Comment by chris-prener** [comment]
hi @FCALVODBAMAF - are you manually entering those 851 addresses like above, or are they in a data frame? 

Also, for `benchmark` and `vintage`, have you tried with the defaults rather than setting them? We're aware of some issues with vintages/benchmarks related to how the API is handling the transition with the 2020 census (see #28).

**Comment by FCALVODBAMAF** [comment]
Hi @chris-prener, I have the 851 adresses in a dataframe that I am passing into the code. I tried it both ways (manually and in a data frame) and I get the same `Empty reply from server` error. 

It seems that I need to specify at least the vintage, if I do not specify it, then I get the error:
`Error in cxy_geocode(data.test, street = "street", city = "city", state = "state",  : 
  `vintage` must be specified for return = 'geographies'`

**Comment by chris-prener** [comment]
Thanks @FCALVODBAMAF - we know folks have been geocoding successfully with the package. Can you geocode those successfully without returning geographies? One possibility is there is a malformed address in your data set causing the API to return an error.

**Comment by FCALVODBAMAF** [comment]
Thanks @chris-prener it seems that is an issue with the batch size. We broke down the 851 into batches of n = 200 and that worked fine, we were able to get the tracts information. I think that could be a great improvement for the package to break down the batches automatically.

**Comment by chris-prener** [comment]
Glad to hear it worked, @FCALVODBAMAF! The package actually does this. Unfortunately, the API can be really challenging to work with. One thing we could do is offer more fine-grained control over how the batches are broken down. Right now we do it for data frames larger than `n = 1000`. My sense has been that this was working fine for folks, but with the transition to 2020 census products, there seems to be a lot more instability in the API right now. I'll go ahead and leave this open so @bransonf and I can touch base about whether end-user specified batch sizes make sense.

**Comment by chris-prener** [comment]
Closing this for now - if other users report issues, we'll address this
