### ISSUE TITLE
Missing Pieces Warning

### ISSUE THREAD

**Issue by chris-prener** [slu-openGIS/censusxy#7]
@bransonf - I'm getting a warning with `censusxy` that I am hoping you can run down the source of. When I geocode, I get `#> Warning: Expected 2 pieces. Missing pieces filled with `NA` in 1 rows [7].` This same warning actually shows up on our [package website](https://slu-opengis.github.io/censusxy/reference/cxy_geocode.html). Thanks for taking a look at this!

reprex to create it:

``` r
test <- dplyr::tibble(
  address = c("1416 Delmar Blvd", "3803 E Dr Martin Luther King Dr", "3700 Lindell Blvd", "3700 Lindell",
              "Lindell Blvd at S Vandeventer Ave", "1420 Delmar Blvd", "Calvary Cemetery"),
  city = c("St. Louis", "St. Louis", "St. Louis", "St. Louis", "St. Louis", "St. Louis", "St. Louis"),
  state = c("MO", "MO", "MO", "MO", "MO", "MO", "MO"),
  zip = c(NA, NA, 63108, 63108, NA, NA , NA)
)

censusxy::cxy_geocode(test, address = "address", city = "city", state  = "state", zip = "zip",
            style = "minimal", output = "tibble", timeout = 30)
#> Warning: Expected 2 pieces. Missing pieces filled with `NA` in 1 rows [7].
#> # A tibble: 7 x 9
#>   address   city  state   zip cxy_status cxy_quality cxy_match    lon   lat
#>   <chr>     <chr> <chr> <dbl> <chr>      <chr>       <chr>      <dbl> <dbl>
#> 1 1416 Del… St. … MO       NA Match      Exact       1416 DELM… -90.2  38.6
#> 2 3803 E D… St. … MO       NA Match      Exact       3803 DR M… -90.2  38.6
#> 3 3700 Lin… St. … MO    63108 Match      Exact       3700 LIND… -90.2  38.6
#> 4 3700 Lin… St. … MO    63108 Match      Non_Exact   3700 LIND… -90.2  38.6
#> 5 Lindell … St. … MO       NA Match      Non_Exact   LINDELL B… -90.2  38.6
#> 6 1420 Del… St. … MO       NA Match      Exact       1420 DELM… -90.2  38.6
#> 7 Calvary … St. … MO       NA No_Match   ""          ""          NA    NA
```

<sup>Created on 2019-09-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bransonf** [comment]
This warning is produced by `tidyr::separate` within the internal `cxy_geocoder()` function. When there is no match, it cannot parse a lon/lat, so it fills with `NA`s. The solution is to wrap with `suppressWarnings({})` or write our own function for seperating.

**Comment by chris-prener** [comment]
is there a way to check for missing lon/lat prior to executing `tidyr::separate`?

**Comment by bransonf** [comment]
Anything with `cxy_status == 'No_Match'` won't have a Lon or Lat.

**Comment by chris-prener** [comment]
separate is being used because what is being returned is `x,y` in the same col?

**Comment by bransonf** [comment]
Exactly

**Comment by chris-prener** [comment]
so my suggestion would to either subset into matched and unmatched, run `tidyr::separate` on the matched object only, and then bind, **or** to put something (perhaps literally `x,y`) into the coordinate col before separating, parse it, and then convert to `NA` and then to `numeric`. Up to you!

**Comment by bransonf** [comment]
I think we're on the same page that we don't want to force in another `supressWarnings` if we don't have to. In which case, I'll just replace `separate` with this anticipated behavior.

**Comment by chris-prener** [comment]
yeah agree there, but not sure I followed your solution? In any event - go ahead and implement something that you think works well and we'll go from there!

**Comment by bransonf** [comment]
See PR #8 for my proposed solution

**Comment by bransonf** [comment]
See PR #9 for my proposed solution.
